language: node_js

git:
  submodules: false
# we track .tar.gz now 

env:
  - BS_TRAVIS_CI=1

after_install: npm link
  
node_js:
  - 6

#
# - 6
# This delays notification

# Not a very reliable service..  
# script: npm run coveralls
# FIXME: instrumentation takes too much time

